# This is a workflow to package and upload on CurseForge and GitHub Releases using BigWigs/Packager

name: Release

# Controls when the action will run.
on:
  # Package alpha version at midnight UTC every Friday
  schedule:
    - cron: '0 18 * * TUE'
  # Triggers the workflow on tag events
  push:
    tags: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # checkout@v2 doesn't pull tags by default now, which results in super long auto changelog, so pull all history incl. tags
          # alternative would be to use checkout@v1
          fetch-depth: 0

      # once cloned, we just run the GitHub Action for the packager project
      - name: Package and release
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_KEY }}
